secret/config/routes.rb
Rails.application.routes.draw do
  
=begin 
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

get 'static_pages/home'

  get 'static_pages/secret_page'

  get 'users/new'

  get 'users/show'

  get 'users/edit'

  get 'users/destroy'
=end

  root to:'static_pages#home'


  resources :users

  get 'static_pages/secret_page', to:'static_pages#secret_page'

  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new' 
	post '/login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'

  post   '/signup',   to: 'users#create'

  post   '/users/:id/edit(.:format)',   to: 'users#edit'

  get    '/users/:id/user/destroy(.:format)', to: 'users#destroy'
  #resources :static_pages

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

secret/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

secret/app/models/user.rb
class User < ApplicationRecord

  attr_accessor :remember_token

  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  class << self
    # Returns the hash digest of the given string.
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

     def forget
    update_attribute(:remember_digest, nil)
  end

end

secret/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
end

secret/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

	def create
		user = User.find_by(email: params[:session][:email].downcase) #le downcase pour éviter que les gens rentre leur emails en capital et du coup pour le matching par la suite ça peut poser problème
		if user && user.authenticate(params[:session][:password]) #si l'utilisateur exite et si on arrive à l'authetifier  fonction donnée par la méthode secure password par la gem decrypt
			#login(cf fonction login dans le helper)
			log_in user
			remember user
			redirect_to user #nous redirige vers la page show du User
		else
			#message erreur
			flash.now[:danger] = 'Invalid email/password comination' #le probléme avec le flash danger, c'est que quand l'utilisateur va passer dans une autre page, il ne s'afface pas. Cf ci dessous l'histoire du flash.now
			render 'new'
		end

  end

  def destroy

  	log_out if logged_in?
  	redirect_to root_url

  end
end

secret/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def secret_page

  	unless 	logged_in?
  		redirect_to login_path
  		flash.now[:danger] = 'Invalid email/password comination' #on voulait mettre un petit flash, mais ça n'a pas marché !
  	end

  end
end

secret/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
  
  	@user = User.new

  end

	def create


        @user = User.new(user_params)

        if @user.save

            log_in @user

            flash[:success] = "Welcome VIP"

            redirect_to @user

        else

            render 'new'

        end


	end

  def show
  
  	@user = User.find(params[:id])

  end

  def edit

  	@user = User.find(params[:id])

  end

 	def update
		
		@user = User.find(params[:id])

     if @user.update(user_params)
   redirect_to user_path
     else
       render 'edit'
     end
	
	end




	def destroy
		

        @user = User.find(params[:id])

        if @user.destroy

            redirect_to root_path

            flash[:success] = 'account deleted'

        end

	end


	private

	def user_params

      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
		
	end

end

secret/app/helpers/application_helper.rb
module ApplicationHelper
end

secret/app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id #envoie un cookie temporaire, et dès que la personne quitte le navigateur la session disparait
	end

	def current_user

		@current_user ||= User.find_by(id: session[:user_id])	
		
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end



	end

	def logged_in?
    !current_user.nil?
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil

	end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

end

secret/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

secret/app/helpers/users_helper.rb
module UsersHelper
end

secret/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">

  <div class="container">

    <%= link_to "home", root_path, id: "logo" %>

    <nav>

      <ul class="nav navbar-nav navbar-right">

        <li><%= link_to "Home", root_path %></li>

        <% if logged_in? %>



          <li class="dropdown">

            <a href="#" class="dropdown-toggle" data-toggle="dropdown">

              Account <b class="caret"></b>

            </a>

            <ul class="dropdown-menu">

              <li><%= link_to "Profile", current_user %></li>

              <li><%= link_to "Settings", '#' %></li>

              <li class="divider"></li>

              <li>

                <%= link_to "Log out", logout_path, method: :delete %>

              </li>

            </ul>

          </li>

        <% else %>

          <li><%= link_to "Log in", login_path %></li>

        <% end %>

      </ul>

    </nav>

  </div>

</header>

secret/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Secret</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

		<!-- Optional theme -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

		<!-- Latest compiled and minified JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	

  </head>

	<%= render "layouts/header" %>

  <body style="margin-top: 100px;">


    <%= yield %>
  </body>
</html>

secret/app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>
<%= link_to "Secret Page", '/static_pages/secret_page' %>

secret/app/views/static_pages/secret_page.html.erb
The secret is inside you !!

secret/app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

secret/app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<h1>Edit</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for@user do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Edit", class: "btn btn-primary" %>
    <% end %>

		<%= link_to 'Delete this account', 'user/destroy'  %>

  </div>
</div>

secret/app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h1>Sign Up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:user, url: signup_path) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Sign Up", class: "btn btn-primary" %>
    <% end %>


  </div>
</div>

secret/app/views/users/show.html.erb
<div style="text-align: center;">

    <h1> <%= @user.name %>'s profile</h1>

    <h2> Ton email : </h2>

    <p><%= @user.email %></p>

    <h2> Ton nom : </h2>

    <p><%= @user.name %></p>

    <% if logged_in? && @user == @current_user %>

    <p><%= link_to 'Editer mon profil', edit_user_path(@user) %></p>

    <% end %>

</div>